<?php

namespace Construct\Internal\Admin;


class AdminController extends \Construct\Controller
{
    public function removeAdminIsAutogeneratedAjax()
    {
        ipRequest()->mustBePost();

        // Removing temporary data
        ipStorage()->remove('Construct', 'adminIsAutogenerated');

        // If user wants to change credentials, redirecting to Administrators list
        if (ipRequest()->getPost('action') == 'change') {
            // todo: redirect and automatically select user and open popup
            $redirect = ipActionUrl(
                    array('aa' => 'Administrators.index')
                ) . "#/hash=&administrator=" . \Construct\Internal\Admin\Backend::userId();

            \Construct\Internal\System\Model::sendUsageStatistics(array('action' => 'Install.adminChange'));
            return \Construct\Response\JsonRpc::result(array('redirect' => $redirect));
        }

        \Construct\Internal\System\Model::sendUsageStatistics(array('action' => 'Install.adminKeep'));
        return \Construct\Response\JsonRpc::result(array('close' => 1));
    }
}
